### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Guppy0608** [ladingwu/python_zhihu#10]
运行index.py时：
Traceback (most recent call last):
  File "....\index.py", line 5, in <module>
    zh=ZhiHu()
  File "...\python_zhihu.py", line 33, in __init__
    self.do_first()
  File "...\python_zhihu.py", line 260, in do_first
    self.login()
  File "...\python_zhihu.py", line 64, in login
    self.xsrf=re.findall('name="_xsrf" value="([\S\s]*?)"',r.text)[0]
IndexError: list index out of range
新手求解答，谢谢各位大佬！

**Comment by Usstzst** [comment]
我也报同样的错误，新手求解答，谢谢各位大佬！

**Comment by ruibukedang0701** [comment]
me too!

**Comment by ZhengDanYang1** [comment]
求解。。

**Comment by linyunhe** [comment]
同！我运行
zh=ZhiHu() 也报同样的错误。

**Comment by linyunhe** [comment]
我知道原因了，知乎现在登陆界面改成了默认【免密码登陆】，所以登陆那里之前的接口不能用了。
